line-length = 100
# Assume the minimum python version
target-version = 'py39'
fix = true

############################
# lint rules
############################
[lint]
select = [
    "E",      # pycodestyle: Error
    "W",      # pycodestyle: Warning
    "F",      # Pyflakes
    "PLE",    # pylint: Error
    "B",      # flake8-bugbear
    "TC",     # flake8-type-checking
    "I",      # isort
    "C4",     # flake8-comprehensions
    "UP",     # pyupgrade
    "ARG001", # unused arguments in functions
    "PERF",   # Perflint
    "RUF",    # Ruff-specific rules
]
unfixable = [
    "F401", # unused imports
    "F841", # unused variables
]
ignore = ["E501", "RUF067"]

[lint.per-file-ignores]
"sn_agent_runner.py" = ["E402"]
