model:
  default: deepseek-v4-pro
  provider: opencode-go
mcp_servers:
  hermes-studio-api:
    command: C:\Users\Admin\.hermes-web-ui\desktop-runtime\hermes\0.19.0\win-x64\node\node.exe
    args:
      - C:\Users\Admin\.hermes-web-ui\desktop-runtime\webui\0.6.32\bin\hermes-studio-mcp.mjs
      - api
    env:
      HERMES_WEB_UI_URL: http://127.0.0.1:8748
      HERMES_WEB_UI_HOME: C:\Users\Admin\.hermes-web-ui
      HERMES_WEBUI_STATE_DIR: C:\Users\Admin\.hermes-web-ui
      HERMES_WEB_UI_PROFILE: bigdata-director
      HERMES_MCP_SERVER_NAME: hermes-studio-api
      HERMES_MCP_TOOLSET: api
      HERMES_WEB_UI_MANAGED_MCP: "1"
    enabled: true
  hermes-studio-devices:
    command: C:\Users\Admin\.hermes-web-ui\desktop-runtime\hermes\0.19.0\win-x64\node\node.exe
    args:
      - C:\Users\Admin\.hermes-web-ui\desktop-runtime\webui\0.6.32\bin\hermes-studio-mcp.mjs
      - devices
    env:
      HERMES_WEB_UI_URL: http://127.0.0.1:8748
      HERMES_WEB_UI_HOME: C:\Users\Admin\.hermes-web-ui
      HERMES_WEBUI_STATE_DIR: C:\Users\Admin\.hermes-web-ui
      HERMES_WEB_UI_PROFILE: bigdata-director
      HERMES_MCP_SERVER_NAME: hermes-studio-devices
      HERMES_MCP_TOOLSET: devices
      HERMES_WEB_UI_MANAGED_MCP: "1"
    enabled: true
  hermes-studio-use:
    command: C:\Users\Admin\.hermes-web-ui\desktop-runtime\hermes\0.19.0\win-x64\node\node.exe
    args:
      - C:\Users\Admin\.hermes-web-ui\desktop-runtime\webui\0.6.32\bin\hermes-studio-mcp.mjs
      - use
    env:
      HERMES_WEB_UI_URL: http://127.0.0.1:8748
      HERMES_WEB_UI_HOME: C:\Users\Admin\.hermes-web-ui
      HERMES_WEBUI_STATE_DIR: C:\Users\Admin\.hermes-web-ui
      HERMES_WEB_UI_PROFILE: bigdata-director
      HERMES_MCP_SERVER_NAME: hermes-studio-use
      HERMES_MCP_TOOLSET: use
      HERMES_WEB_UI_MANAGED_MCP: "1"
    enabled: true
